<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMyWYDcG\appAppKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMyWYDcG/appAppKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerMyWYDcG.legacy');

    return;
}

if (!\class_exists(appAppKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerMyWYDcG\appAppKernelTestDebugContainer::class, appAppKernelTestDebugContainer::class, false);
}

return new \ContainerMyWYDcG\appAppKernelTestDebugContainer([
    'container.build_hash' => 'MyWYDcG',
    'container.build_id' => '973da941',
    'container.build_time' => 1574628685,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMyWYDcG');
