<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.default_xml_metadata_driver' shared service.

$this->privates['doctrine.orm.default_xml_metadata_driver'] = $instance = new \Doctrine\ORM\Mapping\Driver\SimplifiedXmlDriver([(\dirname(__DIR__, 5).'/Resources/config/doctrine') => 'SpomkyLabs\\IpFilterBundle\\Entity', (\dirname(__DIR__, 4).'/TestIpFilterBundle/Resources/config/doctrine') => 'SpomkyLabs\\TestIpFilterBundle\\Entity']);

$instance->setGlobalBasename('mapping');

return $instance;
