<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.security.voter.sl_ip_filter.ip_voter' shared service.

return $this->privates['debug.security.voter.sl_ip_filter.ip_voter'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(($this->privates['sl_ip_filter.ip_voter'] ?? $this->load('getSlIpFilter_IpVoterService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
