<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.cache.pool.cache.app' shared service.

return $this->privates['doctrine.orm.cache.pool.cache.app'] = new \Symfony\Component\Cache\DoctrineProvider(($this->services['cache.app'] ?? $this->load('getCache_AppService.php')));
