<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.default_configuration' shared service.

$this->privates['doctrine.orm.default_configuration'] = $instance = new \Doctrine\ORM\Configuration();

$a = ($this->privates['doctrine.orm.cache.pool.cache.app'] ?? $this->load('getDoctrine_Orm_Cache_Pool_Cache_AppService.php'));

$instance->setEntityNamespaces(['SpomkyLabsIpFilterBundle' => 'SpomkyLabs\\IpFilterBundle\\Entity', 'SpomkyLabsTestIpFilterBundle' => 'SpomkyLabs\\TestIpFilterBundle\\Entity']);
$instance->setMetadataCacheImpl(($this->privates['doctrine.orm.cache.pool.cache.system'] ?? $this->load('getDoctrine_Orm_Cache_Pool_Cache_SystemService.php')));
$instance->setQueryCacheImpl($a);
$instance->setResultCacheImpl($a);
$instance->setMetadataDriverImpl(($this->privates['doctrine.orm.default_metadata_driver'] ?? $this->load('getDoctrine_Orm_DefaultMetadataDriverService.php')));
$instance->setProxyDir(($this->targetDir.''.'/doctrine/orm/Proxies'));
$instance->setProxyNamespace('Proxies');
$instance->setAutoGenerateProxyClasses(false);
$instance->setClassMetadataFactoryName('Doctrine\\ORM\\Mapping\\ClassMetadataFactory');
$instance->setDefaultRepositoryClassName('Doctrine\\ORM\\EntityRepository');
$instance->setNamingStrategy(($this->privates['doctrine.orm.naming_strategy.default'] ?? ($this->privates['doctrine.orm.naming_strategy.default'] = new \Doctrine\ORM\Mapping\DefaultNamingStrategy())));
$instance->setQuoteStrategy(($this->privates['doctrine.orm.quote_strategy.default'] ?? ($this->privates['doctrine.orm.quote_strategy.default'] = new \Doctrine\ORM\Mapping\DefaultQuoteStrategy())));
$instance->setEntityListenerResolver(($this->privates['doctrine.orm.default_entity_listener_resolver'] ?? ($this->privates['doctrine.orm.default_entity_listener_resolver'] = new \Doctrine\Bundle\DoctrineBundle\Mapping\ContainerEntityListenerResolver($this))));
$instance->setRepositoryFactory(($this->privates['doctrine.orm.container_repository_factory'] ?? $this->load('getDoctrine_Orm_ContainerRepositoryFactoryService.php')));

return $instance;
