<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.cache.pool.cache.system' shared service.

return $this->privates['doctrine.orm.cache.pool.cache.system'] = new \Symfony\Component\Cache\DoctrineProvider(($this->services['cache.system'] ?? $this->load('getCache_SystemService.php')));
