<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.default_metadata_driver' shared service.

$this->privates['doctrine.orm.default_metadata_driver'] = $instance = new \Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain();

$a = ($this->privates['doctrine.orm.default_xml_metadata_driver'] ?? $this->load('getDoctrine_Orm_DefaultXmlMetadataDriverService.php'));

$instance->addDriver($a, 'SpomkyLabs\\IpFilterBundle\\Entity');
$instance->addDriver($a, 'SpomkyLabs\\TestIpFilterBundle\\Entity');

return $instance;
