<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sl_ip_filter.range_manager.default' shared service.

return $this->privates['sl_ip_filter.range_manager.default'] = new \SpomkyLabs\IpFilterBundle\Model\RangeManager(($this->services['doctrine'] ?? $this->load('getDoctrineService.php')), 'SpomkyLabs\\TestIpFilterBundle\\Entity\\Range');
