<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sl_ip_filter.ip_voter' shared service.

return $this->privates['sl_ip_filter.ip_voter'] = new \SpomkyLabs\IpFilterBundle\Voter\IpVoter('test', ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->privates['sl_ip_filter.ip_manager.default'] ?? $this->load('getSlIpFilter_IpManager_DefaultService.php')), ($this->privates['sl_ip_filter.range_manager.default'] ?? $this->load('getSlIpFilter_RangeManager_DefaultService.php')));
