<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.user.provider.concrete.in_memory' shared service.

return $this->privates['security.user.provider.concrete.in_memory'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider(['user' => ['password' => 'userpass', 'roles' => [0 => 'ROLE_USER']], 'admin' => ['password' => 'adminpass', 'roles' => [0 => 'ROLE_ADMIN']]]);
